config/routes.rb
Rails.application.routes.draw do
  resources :line_items
  resources :carts
  resources :products do
    resources :comments
  end
  resources :orders
  root 'store#index', as: 'store_index'


  resources :comments
  resources :image_posts
  resources :text_posts
  resources :posts
  resources :users
  resources :sessions

  get 'signup', to: 'users#new', as: 'signup'

  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  # root 'posts#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
has_many :line_items, dependent: :destroy
# Method checks list of items already includes the product if so it adds 1 to the quantity, and if it doesn’t, it builds a new LineItem
def add_product(product)
  current_item = line_items.find_by(product_id: product.id)
  if current_item
    current_item.quantity += 1
  else
    current_item = line_items.build(product_id: product.id)
  end
  current_item
end

# Method to sum the total price for all the products in the cart
# this method is tied to the one in the line_item models need both.
def total_price
  line_items.to_a.sum {|item| item.total_price}
end



end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :product
end

app/models/line_item.rb
class LineItem < ApplicationRecord
  belongs_to :product, optional: true
  belongs_to :cart
  belongs_to :order, optional: true


  # Method to calculate the total price for "x" number of line products
  # this method is tied to the one in the carts models need both.
  def total_price
    product.price * quantity
  end

end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  # Ensures line items that belong to an order are to be destroyed
  # whenever the order is destroyed
  has_many :line_items, dependent: :destroy
  # Validate that payment information is submitted
  validates :name, :address, :email, presence: true


  enum pay_type: {
    "Pay-pal"  => 0,
    "Credit Card" => 1
  }

  # For each item we transfer from the cart to order:
  # 1. set the cart_id = nil thusly prevent the item from being destroied
  # when we destroy the cart.
  # 2. Add the item itself to the line_items collection for the order
  def add_line_items_from_cart(cart)
    cart.line_items.each do |item|
      item.cart.id = nil
      line_items << item
    end
  end
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :line_items
  before_destroy :ensure_not_referenced_by_any_line_item
  has_many :comments
  has_many :orders, through: :line_items
  private

  def ensure_not_referenced_by_any_line_item
    unless line_items.empty?
      errors.add(:base, 'Line Items present')
      throw :abort
    end
  end


end

app/models/user.rb
class User < ApplicationRecord
  has_many :carts
  has_many :orders
  has_secure_password
  validates :email, presence: true, uniqueness: true
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :set_cart, only: [:show, :edit, :update, :destroy]
  rescue_from ActiveRecord::RecordNotFound, with: :invalid_cart
  # GET /carts
  # GET /carts.json
  def index
    @carts = Cart.all
  end

  # GET /carts/1
  # GET /carts/1.json
  def show
  end

  # GET /carts/new
  def new
    @cart = Cart.new
  end

  # GET /carts/1/edit
  def edit
  end

  # POST /carts
  # POST /carts.json
  def create
    @cart = Cart.new(cart_params)

    respond_to do |format|
      if @cart.save
        format.html { redirect_to @cart, notice: 'Cart was successfully created.' }
        format.json { render :show, status: :created, location: @cart }
      else
        format.html { render :new }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /carts/1
  # PATCH/PUT /carts/1.json
  def update
    respond_to do |format|
      if @cart.update(cart_params)
        format.html { redirect_to @cart, notice: 'Cart was successfully updated.' }
        format.json { render :show, status: :ok, location: @cart }
      else
        format.html { render :edit }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carts/1
  # DELETE /carts/1.json
  def destroy
    @cart.destroy if @cart.id == session[:cart_id]
    session[:cart_id] = nil
    respond_to do |format|
      format.html { redirect_to store_index_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cart
      @cart = Cart.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cart_params
      params.fetch(:cart, {})
    end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    @user = User.new
    end

def logout

	session[:company_id] = nil
	flash[:message] = "You are logged out !"
	redirect_to :root



end

  end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  # Gets acess to the current cart
  include CurrentCart
  before_action :set_cart, only: [:new, :create]
  # # checks if cart is empty (logic at bottom in private)
  before_action :ensure_cart_isnt_empty, only: :new
  before_action :set_order, only: [:show, :edit, :update, :destroy]

  # GET /orders
  # GET /orders.json
  def index
    @orders = Order.all
  end

  # GET /orders/1
  # GET /orders/1.json
  def show
  end

  # GET /orders/new
  def new
    @order = Order.new
  end

  # GET /orders/1/edit
  def edit
  end

  # POST /orders
  # POST /orders.json
  def create
    @order = Order.new(order_params)
    # adds into this order the items that are already stored in the cart
    @order.add_line_items_from_cart(@cart)
    @order.user_id = current_user.id
    respond_to do |format|
      # If the save succeeds: 1 ready next order by deleting the cart from the session.
      # 2. Redisplay the catalog
      if @order.save!
        Cart.destroy(session[:cart_id])
        session[:cart_id] = nil
        format.html { redirect_to store_index_url, notice: 'Thank you for your order!' }
        format.json { render :show, status: :created, location: @order }
      else
        format.html { render :new }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orders/1
  # PATCH/PUT /orders/1.json
  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to @order, notice: 'Order was successfully updated.' }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order.destroy
    respond_to do |format|
      format.html { redirect_to orders_url, notice: 'Order was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    def ensure_cart_isnt_empty
      if @cart.line_items.empty?
        redirect_to store_index_url, notice: "Your cart is empty"
      end
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_params
      params.require(:order).permit(:Order, :name, :address, :email, :pay_type)
    end
end

app/controllers/startup_controller.rb
class StartupController < ApplicationController
  def index
  end
end

app/controllers/store_controller.rb
class StoreController < ApplicationController

  def index
    @products = Product.order(:title)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController



def new
  @user = User.new
end

def create
  @user = User.new(user_params)
  if @user.save
    redirect_to store_index_url,
    notice: "Wecome to the site!"
  else
    render "new"

  end
end

private

def user_params
  params.require(:user).permit(:name, :email, :password, :password_confirmation)
end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/startup_helper.rb
module StartupHelper
end

app/helpers/store_helper.rb
module StoreHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/carts/_form.html.erb
<%= form_with(model: cart, local: true) do |form| %>
  <% if cart.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(cart.errors.count, "error") %> prohibited this cart from being saved:</h2>

      <ul>
      <% cart.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/carts/index.html.erb
<p id="notice"><%= notice %></p>
<!-- Header -->


<div class="container">
<div class="col-lg-12 text-center">
<i class="fa fa-user-circle-o fa-5x" aria-hidden="true"></i>
<h1 class= "section-heading" style="color:orange;font-size:400%;font-family:'Contrail One',cursive;">Your Orders</h1>
</div>
</div>

<!-- About -->


  <div class="timeline-panel">
    <div class="container">
      <div class="row">
        <div class="col-lg-12">
    <% @carts.each do |cart| %>
<td id = "cart_id_cell"><%= cart.id %></td>
<td><%= button_to 'View', cart, class: "style" %></td>
<td><%= button_to 'Delete', cart, {method: :delete, class: "style"} %></td>
    <% end %>
  </div>
    </div>
</div>
</div>

app/views/carts/new.html.erb
<h1 class= "section-heading" style="align-items: 'center'; background-color: 'grey';color:orange;font-size:100%;font-family:'Contrail One',cursive;">Orders</h1>




<%= render 'form', cart: @cart %>
<%= link_to 'Back', products_path %>

app/views/carts/show.html.erb
<p id="notice"><%= notice %></p>
  <h1 class= "section-heading" style="color:orange;font-size:400%;font-family:'Contrail One',cursive;">Your Cart</h1>

<div class="cart_summary">
  <table>
    <%@cart.line_items.each do |item|%>
    <tr>
      <td><%= item.quantity %>&times;</td>
      <td><%= item.product.title %></td>
      <td class="item_price"><%= number_to_currency(item.total_price) %></td>
    </tr>
    </div>
    <% end %>

    <tr class="total_line">
      <td colspan="2">Total:</td>
      <td class="total_cell"><%= number_to_currency(@cart.total_price) %></td>
    </tr>

  </table>

  <div class="checkout_button">
    <%= button_to "Checkout", new_order_path, method: :get %>
  </div>



  <div class="delete_button">
  <%= button_to 'Delete', cart_path(@cart), method: :delete %>

  <%= link_to 'Edit', edit_cart_path(@cart) %>

  <%= link_to 'Back', products_path %>
  </div>

app/views/orders/_form.html.erb
<%= form_with(model: order, local: true) do |form| %>
  <% if order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
      <% order.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :order_name, size: 40 %>
  </div>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_area :address, id: :order_address %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email, id: :order_email, size: 40 %>
  </div>

  <div class="field">
    <%= form.label :pay_type %>
    <%= form.select :pay_type, Order.pay_types.keys,
    prompt: "Select a payment method" %>
    <!-- id: :order_pay_type  -->
  </div>

  <div class="actions">
    <%= form.submit 'Place Order' %>
  </div>
<% end %>

app/views/orders/index.html.erb
<p id="notice"><%= notice %></p>

<h1 class= "section-heading" style="color:orange;font-size:500%;font-family:'Contrail One',cursive;">Orders</h1>

<table>
  <thead>
    <tr>
    <th>Name</th>
      <th>Address</th>
      <th>Email</th>
      <th>Pay type</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @orders.each do |order| %>
      <tr>

<%= order.Order %>
<tr>
        <td><%= order.name %></td>
        <td><%= order.address %></td>
        <td><%= order.email %></td>
        <td><%= order.pay_type %></td>
        <td><%= link_to 'Show', order %></td>
        <td><%= link_to 'Edit', edit_order_path(order) %></td>
        <td><%= link_to 'Destroy', order, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Order', new_order_path %>

app/views/orders/new.html.erb
<!-- THis is the template for the form that captures a customer’s details
for checkout -->

<div class="shop_form">
  <fieldset>
<h1 class= "section-heading" style="color:orange;font-size:400%;font-family:'Contrail One',cursive;">Checkout</h1>
<p>please enter your details</p>
    <%= render 'form', order: @order %>
  </fieldset>
</div>

<%= link_to 'Back', products_path %>

app/views/orders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <div class="showOrder">Order</div>

  <%= @order.Order %>
</p>
</div>

<p>
  <strong>Name:</strong>
  <%= @order.name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @order.address %>
</p>

<p>
  <strong>Email:</strong>
  <%= @order.email %>
</p>

<p>
  <strong>Pay type:</strong>
  <%= @order.pay_type %>
</p>

<%= link_to 'Edit', edit_order_path(@order) %> |
<%= link_to 'Back', products_path %>

app/views/users/login.html.erb
<div class="page-header">
  <h1 class= "section-heading" style="color:orange;font-size:500%;font-family:'Contrail One',cursive;">Sign Up</h1>

</div>

<div class="login">
<%= form_tag sessions_path do %>
<div class= "form-group">
  <%= label_tag :Email %>
  <%= email_field_tag :email, params[:email],
  class: "form-control" %>
</div>

<div class="form-group" >
  <% label_tag :Password %>
  <h1>Password</h1>
  <%= password_field_tag :password, nil,
  class: "form-control" %>
</div>

<%= submit_tag "Log In", class: "btn btn-primary" %>
<% end %>
</div>

app/views/users/new.html.erb
<div class= "page-header">
     <div style="height: 40px; width: 150px; margin-bottom: 5px">
  <h1 class= "section-heading" style="color:orange;font-size:500%;font-family:'Contrail One',cursive;">Sign Up</h1>
</div>
</div>

<%= form_for(@user) do |f| %>
<% if @user.errors.any? %>

<div class= "alert alert-danger">
  <strong>

    <%= pluralize(@user.errors.count, "error") %>
    prevented you from signing up:
  </strong>
  <ul>
    <% @user.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
    <% end %>
  </ul>
</div>
<% end %>

    <div class="form-group">
         <div style=" padding-left: 10px;align-content: 'center';font-size: 16px; height: 40px; width: 150px; margin-bottom: 15px">
      <%= f.label :email %>
      <%= f.email_field :email, class: "form-control" %>
    </div>
  </div>

    <div class="form-group">
         <div style=" padding-left: 10px; align-content: 'center';font-size: 16px;height: 40px; width: 150px; margin-bottom: 15px">
      <%= f.label :password %>
      <%= f.password_field :password, class: "form-control" %>
    </div>
  </div>

    <div class="form-group">
         <div style=" padding-top: 10px; padding-left: 10px;align-content: 'center';font-size: 16px;height: 40px; width: 150px; margin-bottom: 80px">
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation, class: "form-control" %>
    </div>
  </div>

<br />
<br />
    <%= f.submit class: "btn btn-primary" %>

    <% end %>

app/views/users/profile.html.erb
<% if user %>
<h1><%= user.first %>'s Profile</h1>
<% if user.photo.url || !me %>
<img src="<%= user.photo.url %>" width="200px">
<% else %>
<form action='/profile' method="POST" enctype="multipart/form-data">
  <input type="file" name="photo">
  <button type="submit">UPLOAD</button>
</form>
<% end %>
<% end %>

  <% @reviews.each do |review| %>
  <div class="review">
    <h3><%= review.event.name %></h3>
    <p><%= review.content %></p>
  </div>
  <%end%>

<% if me %>
  <form action='/users/me/delete' method="POST">
    <button type="submit">delete profile</button>
  </form>
<% end %>

<%= link_to 'New Product', new_product_path %>