config/routes.rb
Rails.application.routes.draw do
  resources :line_items
  resources :carts
  resources :products do
    resources :comments
  end
  resources :orders
  root 'store#index', as: 'store_index'


  resources :comments
  resources :image_posts
  resources :text_posts
  resources :posts
  resources :users
  resources :sessions

  get 'signup', to: 'users#new', as: 'signup'

  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  # root 'posts#index'
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :line_items
  before_destroy :ensure_not_referenced_by_any_line_item
  has_many :comments
  has_many :orders, through: :line_items
  private

  def ensure_not_referenced_by_any_line_item
    unless line_items.empty?
      errors.add(:base, 'Line Items present')
      throw :abort
    end
  end


end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
    @comment = Comment.new
    @comment.product_id = @product.id
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:title, :description, :image_url, :price)
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_comment.html.erb
<div>
  <h1>Comment by <%= comment.author_name %></h1>
  <p class = "comment"> <%=comment.body %></p>
</div>

app/views/products/_form.html.erb
<%= form_with(model: product, local: true) do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :product_title %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, id: :product_description %>
  </div>

  <div class="field">
    <%= form.label :image_url %>
    <%= form.text_field :image_url, id: :product_image_url %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price, id: :product_price %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<%= notice %>



<br>

<div class="xop-section">
  <ul class="xop-grid">
      <% @products.each do |product| %>
      <div class="xop-box">
        <span class="xop-img"><%= image_tag(product.image_url, :class => "stlye-img") %></span>
        <div class="xop-info">
          <h3><%= product.title %></h3>
          <p><%= product.title %></p>
          <p><%= link_to 'Show', product %></p>
          <h3><%= product.price %></h3>
        </div>
        <div class="add_cart"><%= button_to 'Add to Cart', line_items_path(product_id: product) %></div>
      </div>

    <% end %>
  </ul>
</div>

<%= link_to 'New Product', new_product_path %>

app/views/products/new.html.erb
<h1 class= "section-heading" style="color:orange;font-size:500%;font-family:'Contrail One',cursive;">New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>
<!-- layout -->

<div class="content-section">
    <div class="row">
      <div class="col-md-8">
        <div class="product-image">
          <%= image_tag(@product.image_url, :class => "stlye-img") %>
        </div>
        <div class="product-information">
          <h2>STANDARD TELECASTER</h2>
          <p><%= @product.description %></p>
          <p class="product-infos">
            <span>Price: <%= @product.price %></span>
          </p>
          <ul class="product-buttons">
            <div class="add_cart"><%= button_to 'Add to Cart',
            line_items_path(product_id: @product) %></div>
          </ul>
        </div>
        <!-- /.product-information -->
      </div>
      <!-- /.col-md-8 -->

        <div class="product-item-2">
          <strong>Comments: (<%=@product.comments.size%>)</strong>
          <%= render partial: 'products/comment',
          collection: @product.comments.reverse %>

          <%=render partial: 'comments/form' %>

          <%= link_to 'Edit', edit_product_path(@product) %>
          |
          <%= link_to 'Back', products_path %>

        </div>

    </div>

</div>

</body>
</html>