config/routes.rb
Rails.application.routes.draw do
  resources :line_items
  resources :carts
  resources :products do
    resources :comments
  end
  resources :orders
  root 'store#index', as: 'store_index'


  resources :comments
  resources :image_posts
  resources :text_posts
  resources :posts
  resources :users
  resources :sessions

  get 'signup', to: 'users#new', as: 'signup'

  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  # root 'posts#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
has_many :line_items, dependent: :destroy
# Method checks list of items already includes the product if so it adds 1 to the quantity, and if it doesn’t, it builds a new LineItem
def add_product(product)
  current_item = line_items.find_by(product_id: product.id)
  if current_item
    current_item.quantity += 1
  else
    current_item = line_items.build(product_id: product.id)
  end
  current_item
end

# Method to sum the total price for all the products in the cart
# this method is tied to the one in the line_item models need both.
def total_price
  line_items.to_a.sum {|item| item.total_price}
end



end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :product
end

app/models/line_item.rb
class LineItem < ApplicationRecord
  belongs_to :product, optional: true
  belongs_to :cart
  belongs_to :order, optional: true


  # Method to calculate the total price for "x" number of line products
  # this method is tied to the one in the carts models need both.
  def total_price
    product.price * quantity
  end

end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  # Ensures line items that belong to an order are to be destroyed
  # whenever the order is destroyed
  has_many :line_items, dependent: :destroy
  # Validate that payment information is submitted
  validates :name, :address, :email, presence: true


  enum pay_type: {
    "Pay-pal"  => 0,
    "Credit Card" => 1
  }

  # For each item we transfer from the cart to order:
  # 1. set the cart_id = nil thusly prevent the item from being destroied
  # when we destroy the cart.
  # 2. Add the item itself to the line_items collection for the order
  def add_line_items_from_cart(cart)
    cart.line_items.each do |item|
      item.cart.id = nil
      line_items << item
    end
  end
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :line_items
  before_destroy :ensure_not_referenced_by_any_line_item
  has_many :comments
  has_many :orders, through: :line_items
  private

  def ensure_not_referenced_by_any_line_item
    unless line_items.empty?
      errors.add(:base, 'Line Items present')
      throw :abort
    end
  end


end

app/models/user.rb
class User < ApplicationRecord
  has_many :carts
  has_many :orders
  has_secure_password
  validates :email, presence: true, uniqueness: true
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :set_cart, only: [:show, :edit, :update, :destroy]
  rescue_from ActiveRecord::RecordNotFound, with: :invalid_cart
  # GET /carts
  # GET /carts.json
  def index
    @carts = Cart.all
  end

  # GET /carts/1
  # GET /carts/1.json
  def show
  end

  # GET /carts/new
  def new
    @cart = Cart.new
  end

  # GET /carts/1/edit
  def edit
  end

  # POST /carts
  # POST /carts.json
  def create
    @cart = Cart.new(cart_params)

    respond_to do |format|
      if @cart.save
        format.html { redirect_to @cart, notice: 'Cart was successfully created.' }
        format.json { render :show, status: :created, location: @cart }
      else
        format.html { render :new }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /carts/1
  # PATCH/PUT /carts/1.json
  def update
    respond_to do |format|
      if @cart.update(cart_params)
        format.html { redirect_to @cart, notice: 'Cart was successfully updated.' }
        format.json { render :show, status: :ok, location: @cart }
      else
        format.html { render :edit }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carts/1
  # DELETE /carts/1.json
  def destroy
    @cart.destroy if @cart.id == session[:cart_id]
    session[:cart_id] = nil
    respond_to do |format|
      format.html { redirect_to store_index_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cart
      @cart = Cart.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cart_params
      params.fetch(:cart, {})
    end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    @user = User.new
    end

def logout

	session[:company_id] = nil
	flash[:message] = "You are logged out !"
	redirect_to :root



end

  end

app/controllers/store_controller.rb
class StoreController < ApplicationController

  def index
    @products = Product.order(:title)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/startup_helper.rb
module StartupHelper
end

app/helpers/store_helper.rb
module StoreHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ShopApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!-- Bootstrap Custom CSS -->

    <!-- Custom fonts for this template -->
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css">
    <link href='https://fonts.googleapis.com/css?family=Kaushan+Script' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Droid+Serif:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Roboto+Slab:400,100,300,700' rel='stylesheet' type='text/css'>
    <link href="https://fonts.googleapis.com/css?family=Contrail+One" rel="stylesheet">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://blackrockdigital.github.io/startbootstrap-agency/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
  </head>

  <body class='<%= controller.controller_name %>'>
    <div class="pull-right">
      <% if current_user %>

      <% link_to 'Log In', login_path %>


      <% end %>
    </div>
<%= render partial: "home/navbar" %>
    <%= yield %>

    <footer>

</footer>
</body>
</html>